### PR TITLE
update for 14.8

### PR DESCRIPTION
**Pull request by emmaco**

### CODE REVIEW

**Comment by blakesweeney** [comment]
Most changes seem small and generally ok. We did change some cutoffs so I can see why there were changes. However, I don't understand the new classification for RF01704. It is marked as 'mixed' when on the website (https://rfam.org/family/RF01704#tabview=tab4) it looks pretty clearly bacterial to me. Did something happen there?

**Comment by emmaco** [comment]
Well, it used to be be mixed/bacteria and now the % of unclassified sequences rose from 78.67% (unclassified sequences (78.67%), Bacteria (21.33%)) to 85.19% (unclassified sequences (85.19%), Bacteria (14.65%), Viruses (0.16%)).
From checking the script it seems we need at least 90% of sequences to come from a domain to classify it as that domain alone.
If I re-run the script the result is the same. I can check with Nancy to see if this family was changed in this release.

**Comment by emmaco** [comment]
@blakesweeney Yes, RF01704 was updated in this release so the calculations were altered. Is it okay to merge or do you think there could be an issue with the scripts?

**Comment by blakesweeney** [comment]
Maybe I am misunderstanding things then but it looks like from the starburst on the site that it is nearly entirely Bacterial sequences and very few from anywhere else. In fact it appears to be mostly cyanobacteria. I'm not sure why it is saying unclassified.

**Comment by emmaco** [comment]
I’m not sure how the starburst is determined, but the taxonomy csv files seem to be calculated based on the full and seed regions. As per the script - “Compare domains observed in seed alignments and full region hits.”

**Comment by blakesweeney** [comment]
I looked at this and the files seem correct. I think the issue is that the sunburst on the website does not show the unclassified sequences. That is likely a seperate issue so I will merge this.

**Pull request merged**
